#
# Copyright (C) 2000-2006 Wolfgang Denk, DENX Software Engineering, wd@denx.de
#
# SPDX-License-Identifier: GPL-2.0
#

include $(TOPDIR)/config.mk

OBJS-y += net.o
OBJS-y += tftp.o
OBJS-y += bootp.o
OBJS-y += rarp.o
OBJS-y += eth.o
OBJS-y += sntp.o
OBJS-y += httpd.o

include $(TOPDIR)/end.mk