include $(TOPDIR)/config.mk

OBJS-y += main.o
OBJS-y += cmd_bootm.o
OBJS-y += cmd_boot.o
OBJS-y += cmd_echo.o
OBJS-y += cmd_elf.o
OBJS-y += cmd_flash.o
OBJS-y += cmd_help.o
OBJS-y += cmd_mem.o
OBJS-y += cmd_custom.o
OBJS-y += cmd_net.o
OBJS-y += cmd_nvedit.o
OBJS-y += cmd_itest.o
OBJS-y += cmd_load.o
OBJS-y += cmd_qcaclk.o
OBJS-y += cmd_qcagpio.o
OBJS-y += command.o
OBJS-y += console.o
OBJS-y += devices.o
OBJS-y += dlmalloc.o
OBJS-y += environment.o
OBJS-y += env_common.o
OBJS-y += env_nowhere.o
OBJS-y += exports.o
OBJS-y += flash.o
OBJS-y += lists.o
OBJS-y += env_flash.o
OBJS-y += hush.o
OBJS-y += xyzModem.o
OBJS-y += crc16.o
OBJS-y += s_record.o

include $(TOPDIR)/end.mk
