#
# Copyright (C) 2000-2006 Wolfgang Denk, DENX Software Engineering, wd@denx.de
#
# SPDX-License-Identifier: GPL-2.0
#

include $(TOPDIR)/config.mk

BOOTSTRAPOBJ-y	+= cache.o
BOOTSTRAPOBJ-y	+= start_bootstrap.o

OBJS-y	+= start.o
OBJS-y	+= cache.o
OBJS-y	+= cpu.o

include $(TOPDIR)/end.mk